name: Execute

on:
  schedule:
    - cron: '0 13 * 11-12,1-3 3'  # Every wednesday when outside busy season
    - cron: '0 13 * 4-5 *'  # Everyday in April and May, for competition

    - cron: '0 13 1-24 6 3'  # Every wednesday in early June, for virtual competition prep
    - cron: '0 13 24-30 6 *'  # Everyday in late June, for virtual competition
    - cron: '0 13 1-14 7 *'  # Everyday in early July, for virtual competition

    - cron: '0 13 * 9-10 *'  # Everyday in September and October, for kickstart

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('dev-requirements.txt') }}
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run
      run: ./task-bot.py srobo/tasks
